### PR TITLE
intel-parallel-studio-xe 2016

### PR DESCRIPTION
**Pull request by pums974**
I've started to update the PKGBUILD for the 2016 version.
I haven't tested everything.
But I thing that the major part is done.

### CODE REVIEW

**Comment by jonhoo** [comment]
That commit only contains a single change..?

**Comment by pums974** [comment]
No 711 additions and 707 deletions in two files.

**Comment by jonhoo** [comment]
Oh, GitHub is hiding the diff for the PKGBUILD for some reason...

**Comment by jonhoo** [comment]
You might want to rebase against https://github.com/m-wells/intel-parallel-studio-xe. @simon-r [has claimed](https://github.com/simon-r/intel-parallel-studio-xe/issues/12#issuecomment-110245924) that that's the repo of the new maintainer (though I don't know if that's true any more). The PKGBUILD there is certainly more up-to-date than the one in this repo.

**Comment by simon-r** [comment]
That's right I'm no longer the maintainer of this PKG.
https://github.com/m-wells/intel-parallel-studio-xe
https://aur.archlinux.org/pkgbase/intel-parallel-studio-xe/

**Comment by pums974** [comment]
OK, sorry for the inconvenience

**Pull request closed without merging**
